#[path = "ai_policy_smoke.rs"]
pub mod ai_policy_smoke;
#[path = "amp_core_smoke.rs"]
pub mod amp_core_smoke;
#[path = "capability_smoke.rs"]
pub mod capability_smoke;
#[path = "concurrency_smoke.rs"]
pub mod concurrency_smoke;
#[path = "entropy_smoke.rs"]
pub mod entropy_smoke;
#[path = "ipc_pingpong_smoke.rs"]
pub mod ipc_pingpong_smoke;
#[path = "multicore_topology_smoke.rs"]
pub mod multicore_topology_smoke;
#[path = "scheduler_telemetry_smoke.rs"]
pub mod scheduler_telemetry_smoke;
#[path = "telemetry_events_smoke.rs"]
pub mod telemetry_events_smoke;

#[cfg(target_os = "none")]
#[path = "cooperative_sched_smoke.rs"]
pub mod cooperative_sched_smoke;
#[cfg(target_os = "none")]
#[path = "frame_allocator_smoke.rs"]
pub mod frame_allocator_smoke;
#[cfg(target_os = "none")]
#[path = "kernel_mapping_smoke.rs"]
pub mod kernel_mapping_smoke;
#[cfg(target_os = "none")]
#[path = "page_table_install.rs"]
pub mod page_table_install;
#[cfg(target_os = "none")]
#[path = "page_table_smoke.rs"]
pub mod page_table_smoke;
#[cfg(target_os = "none")]
#[path = "service_queue_smoke.rs"]
pub mod service_queue_smoke;
#[cfg(target_os = "none")]
#[path = "task_smoke.rs"]
pub mod task_smoke;
